Create quick-installerOSX.sh
LangLangBart/boonGUI pull request #62
Opened 2021-11-20 23:57 UTC by Pretuer

2021-11-21 11:15 UTC, LangLangBart requested changes
Could be included under installation of the README file, would look nice with a expand element. 
https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

2021-11-21 11:15 UTC, LangLangBart commented on quick-installerOSX.sh
> +#!/bin/zsh
#!/bin/sh
https://support.apple.com/guide/terminal/about-shell-scripts-apd53500956-7c5b-496b-a362-2845f2aab4bc/mac

2021-11-21 11:15 UTC, LangLangBart commented on quick-installerOSX.sh
> +cd ~/Library/Application\Support/0ad/mods/
cd ~/Library/Application\ Support/0ad/mods/
 missing space

2021-11-21 11:15 UTC, LangLangBart commented on quick-installerOSX.sh
> +pwd
why do u need "pwd" ?

2021-11-21 11:15 UTC, LangLangBart commented on quick-installerOSX.sh
> +0ad
what is this for?

2021-11-22 06:03 UTC, Pretuer commented on quick-installerOSX.sh
> +pwd
it's redundant i'll delete it

2021-11-22 06:07 UTC, Pretuer commented on quick-installerOSX.sh
> +0ad
would've automatically ran the game, but i've removed it

2021-11-22 12:12 UTC, LangLangBart commented
Thanks.

2021-11-22 12:13 UTC, merged